[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Remove the ignore command as it might be causing issues
# Remove the Lighthouse plugin as it's not essential for deployment 