[build]
  command = "npm install --include=dev && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "10.9.2"
  NODE_ENV = "production"
  CI = "false"

# Remove Next.js plugin as it's not needed for Vite 