[build]
  command = "npm install --omit=optional --no-audit --no-fund && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "10.9.2"
  NODE_ENV = "production"
  CI = "false"
  NPM_CONFIG_LOGLEVEL = "error"
  NPM_CONFIG_OMIT = "optional"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_UPDATE_NOTIFIER = "false"

# Remove Next.js plugin as it's not needed for Vite 