[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "10.9.2"
  NODE_ENV = "production"

[[build.plugins]]
  package = "@netlify/plugin-nextjs"
  [build.plugins.inputs]
    nextConfigDir = "."

# Remove the ignore command as it might be causing issues
# Remove the Lighthouse plugin as it's not essential for deployment 